<?php


namespace Tests\Feature\Warehouse;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class GetDeliveryOptionTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::factory()->create();
        $this->actingAs($user, 'api');
        $this->artisan("db:seed --class=DeliveryOptionsSeeder");
    }

    /** @test */
    public function it_should_get_the_delivery_option() {

        // Given
        $country = "Nederland";
        $deliveryOptionName = "PostNL - Pakket";
        $carrierName = "PostNL";
        $url = route("get-delivery-option");

        // When
        $response = $this->post($url, [
            "delivery_country" => $country,
            "delivery_option_name" => $deliveryOptionName,
            "carrier_name" => $carrierName
        ]);

        // Then
        $response->assertOk();
        self::assertEquals(3085, $response["payload"]["delivery_option"]["product_code"]);
    }
}
