<?php


namespace Tests\Unit\Warehouse;


use App\SharedKernel\AddressFactory;
use App\Warehouse\Domain\Parties\Customer;
use Tests\TestCase;

class CustomerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_set_first_and_last_name()
    {
        $firstName = "Kees";
        $lastName = "de Vries";
        $address = AddressFactory::homeDesignShops();
        $email = "kees@devries.nl";
        $contactName = "Kees de Vries";
        $phoneNumber = "0612345678";

        $customer = new Customer(null, "1234", null, $address, $address, $address, $email, $contactName, $phoneNumber, null, $firstName, $lastName);

        self::assertEquals("Kees", $customer->firstName());
        self::assertEquals("de Vries", $customer->lastName());
    }
}
