<?php


namespace Tests\Unit\Warehouse;


use App\Warehouse\Domain\Orders\DeliveryOption;
use Tests\TestCase;

class DeliveryOptionTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_have_the_correct_attributes() {

        // Given
        $carrierName = "Post NL";
        $name = "PostNL - Afhaalpunt";
        $productCode = 3533;
        $characteristic = null;
        $option = null;

        // When
        $deliveryOption = new DeliveryOption($carrierName, $name, $productCode, $characteristic, $option);

        // Then
        self::assertEquals($name, $deliveryOption->name());
        self::assertEquals($productCode, $deliveryOption->productCode());
        self::assertEquals($characteristic, $deliveryOption->characteristic());
        self::assertEquals($option, $deliveryOption->option());
    }
}
