<?php


namespace Tests\Unit\Warehouse;


use App\Warehouse\Domain\Orders\OrderFactory;
use App\Warehouse\Domain\Services\ReviewRequestSenderServiceInterface;
use Tests\Feature\Warehouse\DummyReviewRequestSenderService;
use Tests\TestCase;

class OrderFactoryTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app->bind(ReviewRequestSenderServiceInterface::class, DummyReviewRequestSenderService::class);

    }

    /** @test */
    public function it_should_create_multiple_orders()
    {
        // Given
        $amount = 10;

        // When
        $orders = OrderFactory::create($amount);

        // Then
        self::assertEquals($amount, sizeof($orders));
    }
}
