<?php


namespace Tests\Unit\Warehouse;


use App\Warehouse\Domain\Exporters\PackingSlipGeneratorInterface;
use App\Warehouse\Domain\Mails\TrackAndTraceMail;
use App\Warehouse\Domain\Orders\OrderFactory;
use App\Warehouse\Domain\Services\ReviewRequestSenderServiceInterface;
use App\Warehouse\Domain\Shipments\PackingSlip;
use App\Warehouse\Domain\Shipments\ShipmentFactory;
use Tests\Feature\Warehouse\DummyPackingSlipGenerator;
use Tests\Feature\Warehouse\DummyReviewRequestSenderService;
use Tests\TestCase;

class TrackAndTraceEmailTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->app->bind(PackingSlipGeneratorInterface::class, DummyPackingSlipGenerator::class);
        $this->app->bind(ReviewRequestSenderServiceInterface::class, DummyReviewRequestSenderService::class);

    }

    /** @test */
    public function it_should_have_the_correct_subject()
    {
        // Given
        $order = OrderFactory::constantUnprocessed();
        $customer = $order->customer();

        $shipment = ShipmentFactory::create($order->reference());
        $packingSlip = new PackingSlip('Test-Packing-Slip-Path', 'test-packing-slip-url');

        // When
        $mail = new TrackAndTraceMail($customer, $order, $shipment, $packingSlip);

        // Then
        self::assertEquals($customer->contactName().", uw bestelling is verzonden", $mail->subject());
    }

}
