<?php

namespace Tests\Unit\Warehouse\Domain\Picklists;

use App\Warehouse\Domain\Exceptions\PicklistOperationException;
use App\Warehouse\Domain\Picklists\PicklistFactory;
use Carbon\CarbonImmutable;
use Tests\TestCase;

class PicklistTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_change_preferred_delivery_date_when_snooze_until_is_after_today()
    {
        // Given
        $picklist = PicklistFactory::dummy();
        $picklist->snoozeUntil(CarbonImmutable::now()->nextWeekday());

        // When
        $preferredDeliveryDate = CarbonImmutable::now();
        $picklist->changePreferredDeliveryDate($preferredDeliveryDate);

        // Then
        self::assertEquals($preferredDeliveryDate, $picklist->preferredDeliveryDate());
    }

    /** @test */
    public function it_should_change_preferred_delivery_date_when_snooze_until_is_before_today()
    {
        // Given
        $picklist = PicklistFactory::dummy();
        $picklist->snoozeUntil(CarbonImmutable::now()->previousWeekday());

        // When
        $preferredDeliveryDate = CarbonImmutable::now();
        $picklist->changePreferredDeliveryDate($preferredDeliveryDate);

        // Then
        self::assertEquals($preferredDeliveryDate, $picklist->preferredDeliveryDate());
    }

    /** @test */
    public function it_should_throw_exception_when_changing_delivery_date_and_snooze_until_is_today()
    {
        // Then
        $this->expectException(PicklistOperationException::class);
        $this->expectErrorMessage('Kan bezorgdatum niet wijzigen, omdat de picklijst is gesnoozed tot vandaag. Overleg met logistiek om de wijzigin alsnog door te voeren.');

        // Given
        $picklist = PicklistFactory::dummy();
        $picklist->snoozeUntil(CarbonImmutable::now());

        // When
        $preferredDeliveryDate = CarbonImmutable::now();
        $picklist->changePreferredDeliveryDate($preferredDeliveryDate);
    }

    /** @test */
    public function it_should_change_delivery_date_when_snooze_until_is_today_but_discussed_with_logistics_department()
    {
        // Given
        $picklist = PicklistFactory::dummy();
        $picklist->snoozeUntil(CarbonImmutable::now());

        // When
        $preferredDeliveryDate = CarbonImmutable::now();
        $picklist->changePreferredDeliveryDate($preferredDeliveryDate, true);

        // Then
        self::assertEquals($preferredDeliveryDate, $picklist->preferredDeliveryDate());
    }
}
